import { useState } from "react"
import svgDetail from "@/imports/DetailScreen/svg-8kiebeh0qh"
import svgUpload from "@/imports/UploadInitialScreen/svg-wqv28lyrjs"

export type Verdict="danger"|"caution"|"uncertain"
export interface AnalysisResult{verdict:Verdict;similarity:number;similarCount:number;malwareName?:string;malwareCategory?:string;matchType?:"EXACT"|"VECTOR"|"NONE";evidenceSummary?:string;recommendedActions?:string[]}
const COLORS={danger:{bg:"#fff1f1",color:"#FF5C5C"},caution:{bg:"#FFF7E6",color:"#F59E0B"},uncertain:{bg:"#f4f6fb",color:"#94a3b8"}}
function StatusBar(){return <div className="flex h-[44px] items-center justify-between px-[24px]"><p className="font-['Pretendard'] font-semibold text-[#0f172a] text-[15px]">9:41</p><svg className="size-[18px]" fill="none" viewBox="0 0 18 18"><path clipRule="evenodd" d={svgUpload.pc062070} fill="#0F172A" fillRule="evenodd"/></svg></div>}
function BackHeader({onBack,onMenuOpen}:{onBack:()=>void;onMenuOpen:()=>void}){return <div className="bg-white flex h-[56px] items-center justify-between px-[24px]"><div className="flex gap-[12px] items-center"><button onClick={onBack} className="size-[24px]"><svg className="size-full" fill="none" viewBox="0 0 24 24"><path d="M15 18L9 12L15 6" stroke="#1B3A5C" strokeLinecap="round" strokeWidth="2"/></svg></button><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[18px]">분석 상세 정보</p></div><button onClick={onMenuOpen} className="size-[24px]"><svg className="size-full" fill="none" viewBox="0 0 24 24"><path d={svgDetail.p15b88b00} stroke="#1B3A5C" strokeLinecap="round" strokeWidth="2"/></svg></button></div>}
function HomeIndicator(){return <div className="flex justify-center py-[12px]"><div className="bg-[#0f172a] h-[5px] rounded-full w-[134px]"/></div>}
export function DetailScreen({appName,result,onBack,onMenuOpen}:{appName:string;result:AnalysisResult;onBack:()=>void;onMenuOpen:()=>void}){const[open,setOpen]=useState(true);const c=COLORS[result.verdict];const method=result.matchType==="EXACT"?"정확 일치":result.matchType==="VECTOR"?"Vector 유사도 검색":"판단 근거 부족";return <div className="bg-[#f8fafb] flex flex-col justify-between w-full min-h-full"><div className="flex-1 overflow-y-auto"><StatusBar/><BackHeader onBack={onBack} onMenuOpen={onMenuOpen}/><div className="flex flex-col gap-[20px] p-[24px]"><div><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[15px] mb-[12px]">유사 악성 앱 정보</p><div className="bg-white rounded-[12px] border border-[#ebeff3] p-[16px] flex flex-col gap-[10px]"><div className="flex justify-between gap-[12px]"><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[14px] break-all">{result.malwareName||appName}</p><p className="font-['Pretendard'] font-bold text-[12px] shrink-0" style={{color:c.color}}>유사도 {result.similarity}%</p></div><div className="bg-[#e2e8f0] h-[6px] rounded-[3px] overflow-hidden"><div className="h-full" style={{width:`${result.similarity}%`,backgroundColor:c.color}}/></div>{result.malwareCategory&&<p className="font-['Pretendard'] text-[#64748b] text-[12px]">유형: {result.malwareCategory}</p>}<p className="font-['Pretendard'] text-[#64748b] text-[12px]">판정 방식: {method}</p></div></div><div><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[15px] mb-[12px]">위험 판단 이유</p><div className="bg-white rounded-[12px] border border-[#ebeff3] p-[16px]"><button onClick={()=>setOpen(v=>!v)} className="flex justify-between w-full"><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[14px]">Python AI 판정 근거</p><span className="text-[#64748b]">{open?"⌃":"⌄"}</span></button>{open&&<p className="font-['Pretendard'] leading-[1.5] text-[#64748b] text-[13px] mt-[8px]">{result.evidenceSummary||"저장된 판정 근거가 없습니다."}</p>}</div></div>{result.recommendedActions?.length?<div><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[15px] mb-[12px]">권장 행동</p><div className="bg-white rounded-[16px] border border-[#ebeff3] p-[16px] flex flex-col gap-[10px]">{result.recommendedActions.map(a=><div key={a} className="flex gap-[10px] items-start"><div className="mt-[5px] size-[7px] rounded-full shrink-0" style={{backgroundColor:c.color}}/><p className="font-['Pretendard'] text-[#64748b] text-[13px] leading-[1.5]">{a}</p></div>)}</div></div>:null}<div className="rounded-[12px] p-[14px]" style={{backgroundColor:c.bg}}><p className="font-['Pretendard'] text-[#64748b] text-[12px] leading-[1.5]">분석 결과는 팀 탐지 데이터 및 AI 유사도 검색을 이용한 보조 정보입니다. UNKNOWN은 안전 판정이 아닙니다.</p></div></div></div><HomeIndicator/></div>}
