import { useEffect, useState } from "react"
import svgUpload from "@/imports/UploadInitialScreen/svg-wqv28lyrjs"
import imgHeaderLogo from "@/imports/image-4.png"

interface LoadingScreenProps { isComplete: boolean; onDone: () => void; onMenuOpen: () => void; onLogoClick: () => void }
function StatusBar(){return <div className="flex h-[44px] items-center justify-between px-[24px]"><p className="font-['Pretendard'] font-semibold text-[#0f172a] text-[15px]">9:41</p><svg className="size-[18px]" fill="none" viewBox="0 0 18 18"><path clipRule="evenodd" d={svgUpload.pc062070} fill="#0F172A" fillRule="evenodd" /></svg></div>}
function BrandHeader({onMenuOpen,onLogoClick}:{onMenuOpen:()=>void;onLogoClick:()=>void}){return <div className="bg-white flex h-[56px] items-center justify-between px-[24px]"><button onClick={onLogoClick} className="flex gap-[12px] items-center"><img alt="닿음 로고" className="size-[36px] object-contain" src={imgHeaderLogo}/><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[18px]">닿음</p></button><button onClick={onMenuOpen} className="size-[24px]"><svg className="size-full" fill="none" viewBox="0 0 24 24"><path d={svgUpload.p15b88b00} stroke="#1B3A5C" strokeLinecap="round" strokeWidth="2" /></svg></button></div>}
function HomeIndicator(){return <div className="flex justify-center py-[12px]"><div className="bg-[#0f172a] h-[5px] rounded-full w-[134px]"/></div>}
export function LoadingScreen({isComplete,onDone,onMenuOpen,onLogoClick}:LoadingScreenProps){const[dots,setDots]=useState(1);useEffect(()=>{const t=setInterval(()=>setDots(v=>(v%3)+1),600);return()=>clearInterval(t)},[]);useEffect(()=>{if(!isComplete)return;const t=setTimeout(onDone,650);return()=>clearTimeout(t)},[isComplete,onDone]);return <div className="bg-[#f8fafb] flex flex-col justify-between w-full min-h-full"><div><StatusBar/><BrandHeader onMenuOpen={onMenuOpen} onLogoClick={onLogoClick}/><div className="flex flex-col gap-[32px] items-center p-[24px]"><div className="flex flex-col gap-[24px] items-center pt-[40px]"><div className="relative flex items-center justify-center size-[116px]"><div className={`absolute inset-0 rounded-full border-[3px] ${isComplete?"":"animate-spin"}`} style={{borderColor:isComplete?"#a7f3d0":"#c5d8ff",borderTopColor:isComplete?"#059669":"#4F8CFF"}}/><div className="flex items-center justify-center rounded-full size-[100px]" style={{backgroundColor:isComplete?"#ecfdf5":"#ebf0ff"}}><div className="bg-white flex items-center justify-center rounded-full size-[70px]"><svg className="size-[32px]" fill="none" viewBox="0 0 32 32"><circle cx="16" cy="16" r="11" stroke={isComplete?"#059669":"#4F8CFF"} strokeWidth="2"/><path d={isComplete?"M10.5 16l3.5 3.5 7.5-7.5":"M12 16h8M16 12v8"} stroke={isComplete?"#059669":"#4F8CFF"} strokeLinecap="round" strokeWidth="2"/></svg></div></div></div><div className="text-center"><p className={`font-['Pretendard'] font-bold text-[18px] ${isComplete?"text-[#059669]":"text-[#1b3a5c]"}`}>{isComplete?"분석이 완료되었어요!":"AI가 화면을 분석하고 있어요"}</p><p className="font-['Pretendard'] text-[#64748b] text-[13px] mt-[8px]">{isComplete?"결과 화면으로 이동합니다":`인식된 앱 정보를 보안 데이터와 비교하고 있어요${"·".repeat(dots)}`}</p></div></div><div className="p-[20px] rounded-[16px] w-full" style={{background:"linear-gradient(135deg, #ebf0ff 0%, #ebe8ff 100%)"}}><p className="font-['Pretendard'] font-bold text-[#7B6CFF] text-[14px]">분석 기준</p><p className="font-['Pretendard'] font-medium leading-[1.5] text-[#1b3a5c] text-[14px] mt-[8px]">등록된 위험 데이터는 정확 일치로 확인하고, 미등록 항목은 Python AI가 유사도를 비교합니다.</p></div></div></div><HomeIndicator/></div>}
