import { useState } from "react"
import svgGuide from "@/imports/ParentGuideScreen/svg-w77zqixszq"
import svgDetail from "@/imports/DetailScreen/svg-8kiebeh0qh"
import svgUpload from "@/imports/UploadInitialScreen/svg-wqv28lyrjs"

export type Verdict="danger"|"caution"|"uncertain"
export interface AnalysisResult{verdict:Verdict;similarity:number;similarCount:number;parentMessage?:string;recommendedActions?:string[]}
const VC={danger:{bg:"#fff1f1",border:"#FF5C5C",text:"#FF5C5C",label:"위험 수준 매우 높음"},caution:{bg:"#FFF7E6",border:"#F59E0B",text:"#B45309",label:"확인 필요"},uncertain:{bg:"#f4f6fb",border:"#c0cbdc",text:"#7B8FAD",label:"판단 보류"}}
function defaultGuide(appName:string,verdict:Verdict){if(verdict==="danger")return `부모님, '${appName}' 앱에서 높은 위험 신호가 확인됐어요. 확인이 끝날 때까지 앱 사용과 개인정보 입력을 멈춰 주세요.`;if(verdict==="caution")return `부모님, '${appName}' 앱은 추가 확인이 필요해요. 설치 출처와 권한을 함께 확인해 주세요.`;return `부모님, '${appName}' 앱은 현재 정보만으로 위험하거나 안전하다고 확정하기 어려워요. 출처를 먼저 확인해 주세요.`}
function StatusBar(){return <div className="flex h-[44px] items-center justify-between px-[24px]"><p className="font-['Pretendard'] font-semibold text-[#0f172a] text-[15px]">9:41</p><svg className="size-[18px]" fill="none" viewBox="0 0 18 18"><path clipRule="evenodd" d={svgUpload.pc062070} fill="#0F172A" fillRule="evenodd"/></svg></div>}
function BackHeader({onBack,onMenuOpen}:{onBack:()=>void;onMenuOpen:()=>void}){return <div className="bg-white flex h-[56px] items-center justify-between px-[24px]"><div className="flex gap-[12px] items-center"><button onClick={onBack} className="size-[24px]"><svg className="size-full" fill="none" viewBox="0 0 24 24"><path d="M15 18L9 12L15 6" stroke="#1B3A5C" strokeLinecap="round" strokeWidth="2"/></svg></button><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[18px]">부모님용 안내문</p></div><button onClick={onMenuOpen} className="size-[24px]"><svg className="size-full" fill="none" viewBox="0 0 24 24"><path d={svgDetail.p15b88b00} stroke="#1B3A5C" strokeLinecap="round" strokeWidth="2"/></svg></button></div>}
function HomeIndicator(){return <div className="flex justify-center py-[12px]"><div className="bg-[#0f172a] h-[5px] rounded-full w-[134px]"/></div>}
export function ParentGuideScreen({appName,result,onBack,onMenuOpen,onAnalyzeAnother}:{appName:string;result:AnalysisResult;onBack:()=>void;onMenuOpen:()=>void;onAnalyzeAnother:()=>void}){const[copied,setCopied]=useState(false);const v=VC[result.verdict];const guide=[result.parentMessage||defaultGuide(appName,result.verdict),...(result.recommendedActions?.length?["","확인할 내용",...result.recommendedActions.map(a=>`• ${a}`)]:[])].join("\n");const copy=async()=>{try{await navigator.clipboard.writeText(guide)}catch{const ta=document.createElement("textarea");ta.value=guide;document.body.appendChild(ta);ta.select();document.execCommand("copy");document.body.removeChild(ta)}setCopied(true);setTimeout(()=>setCopied(false),2500)};return <div className="bg-[#f8fafb] flex flex-col justify-between w-full min-h-full"><div className="flex-1 overflow-y-auto"><StatusBar/><BackHeader onBack={onBack} onMenuOpen={onMenuOpen}/><div className="flex flex-col gap-[24px] p-[24px]"><div><p className="font-['Pretendard'] font-bold text-[#1b3a5c] text-[20px]">부모님께 보낼 안내문</p><p className="font-['Pretendard'] text-[#64748b] text-[14px] mt-[8px]">Python AI가 판정 근거를 바탕으로 만든 쉬운 안내입니다.</p></div><div className="bg-white rounded-[16px] border border-[#ebeff3] p-[20px] flex flex-col gap-[16px]"><div className="flex justify-between"><p className="font-['Pretendard'] font-bold text-[#7B6CFF] text-[12px]">안내문 미리보기</p><svg className="size-[16px]" fill="none" viewBox="0 0 16 16"><path d={svgGuide.p2d6e42c0} stroke="#7B6CFF" strokeLinecap="round" strokeWidth="2"/></svg></div><p className="font-['Pretendard'] leading-[1.6] text-[#1b3a5c] text-[14px] whitespace-pre-wrap">{guide}</p></div><div className="flex justify-center"><div className="px-[12px] py-[6px] rounded-full" style={{backgroundColor:v.bg,border:`1px solid ${v.border}`}}><p className="font-['Pretendard'] font-semibold text-[11px]" style={{color:v.text}}>{v.label}</p></div></div></div></div><div className="flex flex-col gap-[8px] pb-[8px] px-[24px]">{copied&&<div className="bg-[#ecfdf5] border border-[#059669] rounded-[12px] p-[12px] text-center"><p className="font-['Pretendard'] font-semibold text-[#059669] text-[13px]">복사되었습니다</p></div>}<button onClick={copy} className="h-[54px] rounded-[14px] text-white font-['Pretendard'] font-bold text-[16px]" style={{background:"linear-gradient(90deg, #4F8CFF 0%, #7B6CFF 100%)"}}>클립보드에 복사하기</button><button onClick={onAnalyzeAnother} className="bg-white h-[42px] rounded-[12px] border border-[#e2e8f0] font-['Pretendard'] text-[#64748b] text-[13px]">다른 앱 분석하기</button><HomeIndicator/></div></div>}
