server:
  port: 8080
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY}

spring:
  application:
    name: dahum-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      maximum-pool-size: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

dahum:
  ai:
    base-url: ${AI_BASE_URL}
  public-base-url: ${PUBLIC_BASE_URL}
